<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ECDRNt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ECDRNt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ECDRNt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ECDRNt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ECDRNt\App_KernelDevDebugContainer([
    'container.build_hash' => '5ECDRNt',
    'container.build_id' => '90a10018',
    'container.build_time' => 1677522402,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ECDRNt');
