<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA3ax4zM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA3ax4zM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA3ax4zM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA3ax4zM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA3ax4zM\App_KernelDevDebugContainer([
    'container.build_hash' => 'A3ax4zM',
    'container.build_id' => '879842f7',
    'container.build_time' => 1676374776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA3ax4zM');
