<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\RegistrationController::list'], [], [['text', '/list']], [], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\RegistrationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'user_update' => [['id'], ['_controller' => 'App\\Controller\\RegistrationController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\SecurityController::home'], [], [['text', '/home']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
