<<<<<<< HEAD
controllers:
    resource: ../src/Controller/
    type: attribute
matches_events:
    path: /matches/events
    controller: App\Controller\MatchesController::events

matches_show:
    path: /matches/{id}
    controller: App\Controller\MatchesController::show


matches_details:
    path: /matches/{id}
    controller: App\Controller\MatchesController::details
    requirements:
        id: '\d+'
=======
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
add_to_cart:
    path: '/produit/add/{id}'
    controller: 'App\Controller\CartController::add'
>>>>>>> origin/GestionProduit
