controllers:
    resource: ../src/Controller/
    type: attribute
matches_events:
    path: /matches/events
    controller: App\Controller\MatchesController::events

matches_show:
    path: /matches/{id}
    controller: App\Controller\MatchesController::show


matches_details:
    path: /matches/{id}
    controller: App\Controller\MatchesController::details
    requirements:
        id: '\d+'
