twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
=======
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
>>>>>>> origin/GestionUser

when@test:
    twig:
        strict_variables: true
